version: '3.9'

services:
  lite-lms:
    container_name: podium-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ".env.local"
    volumes:
      - /var/recordings:/var/recordings

  egress:
    image: livekit/egress
    container_name: livekit-egress
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./egress.yaml:/etc/livekit/egress.yaml
      - /var/recordings:/var/recordings
    environment:
      - EGRESS_CONFIG_FILE=/etc/livekit/egress.yaml
